include = [
    "**/*.toml",
]

[formatting]
align_entries       = true
allowed_blank_lines = 1
array_auto_collapse = false
compact_arrays      = false
crlf                = false
indent_string       = '    '
reorder_keys        = true
