CREATE TABLE release_disc (
  id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  release_id INT NOT NULL REFERENCES release(id),
  name TEXT,
  UNIQUE(id, release_id)
);

CREATE TABLE release_disc_history (
  id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  history_id INT NOT NULL REFERENCES release_history(id),
  name TEXT
);

ALTER TABLE
  release_track
ADD
  COLUMN disc_id INT NOT NULL REFERENCES release_disc(id);

ALTER TABLE
  release_track_history
ADD
  COLUMN disc_history_id INT NOT NULL REFERENCES release_disc_history(id);
