[package]
edition = "2024"
name    = "migration"
publish = false
version = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration.workspace = true
tokio.workspace             = true
