//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "artist_localized_name_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub artist_history_id: i32,
    pub language_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist_history::Entity",
        from = "Column::ArtistHistoryId",
        to = "super::artist_history::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArtistHistory,
    #[sea_orm(
        belongs_to = "super::language::Entity",
        from = "Column::LanguageId",
        to = "super::language::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Language,
}

impl Related<super::artist_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistHistory.def()
    }
}

impl Related<super::language::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Language.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
