//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "change_request_history")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub change_request_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub history_id: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::change_request::Entity",
        from = "Column::ChangeRequestId",
        to = "super::change_request::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChangeRequest,
}

impl Related<super::change_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
