//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "credit_role")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub short_description: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credit_role_inheritance_history::Entity")]
    CreditRoleInheritanceHistory,
    #[sea_orm(has_many = "super::group_member_role::Entity")]
    GroupMemberRole,
    #[sea_orm(has_many = "super::group_member_role_history::Entity")]
    GroupMemberRoleHistory,
    #[sea_orm(has_many = "super::release_credit::Entity")]
    ReleaseCredit,
    #[sea_orm(has_many = "super::release_credit_history::Entity")]
    ReleaseCreditHistory,
    #[sea_orm(has_many = "super::song_credit::Entity")]
    SongCredit,
    #[sea_orm(has_many = "super::song_credit_history::Entity")]
    SongCreditHistory,
}

impl Related<super::credit_role_inheritance_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditRoleInheritanceHistory.def()
    }
}

impl Related<super::group_member_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMemberRole.def()
    }
}

impl Related<super::group_member_role_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMemberRoleHistory.def()
    }
}

impl Related<super::release_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCredit.def()
    }
}

impl Related<super::release_credit_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCreditHistory.def()
    }
}

impl Related<super::song_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongCredit.def()
    }
}

impl Related<super::song_credit_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongCreditHistory.def()
    }
}

impl Related<super::group_member::Entity> for Entity {
    fn to() -> RelationDef {
        super::group_member_role::Relation::GroupMember.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::group_member_role::Relation::CreditRole.def().rev())
    }
}

impl Related<super::group_member_history::Entity> for Entity {
    fn to() -> RelationDef {
        super::group_member_role_history::Relation::GroupMemberHistory.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::group_member_role_history::Relation::CreditRole
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
