//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "group_member_join_leave")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_member_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub join_year: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub leave_year: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_member::Entity",
        from = "Column::GroupMemberId",
        to = "super::group_member::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GroupMember,
}

impl Related<super::group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
