//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{JoinYearType, LeaveYearType};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "group_member_join_leave_history")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_member_history_id: i32,
    pub join_year: Option<i16>,
    pub leave_year: Option<i16>,
    pub join_year_type: JoinYearType,
    pub leave_year_type: LeaveYearType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_member_history::Entity",
        from = "Column::GroupMemberHistoryId",
        to = "super::group_member_history::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GroupMemberHistory,
}

impl Related<super::group_member_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMemberHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
