//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "group_member")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub member_id: i32,
    pub group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::GroupId",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist2,
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::MemberId",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist1,
    #[sea_orm(has_many = "super::group_member_join_leave::Entity")]
    GroupMemberJoinLeave,
    #[sea_orm(has_many = "super::group_member_role::Entity")]
    GroupMemberRole,
}

impl Related<super::group_member_join_leave::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMemberJoinLeave.def()
    }
}

impl Related<super::group_member_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupMemberRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
