//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::DatePrecision;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "label_history")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub founded_date: Option<Date>,
    pub founded_date_precision: DatePrecision,
    pub dissolved_date: Option<Date>,
    pub dissolved_date_precision: DatePrecision,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::label_localized_name_history::Entity")]
    LabelLocalizedNameHistory,
}

impl Related<super::label_localized_name_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelLocalizedNameHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
