//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::DatePrecision;

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "label_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub founded_date: Option<Date>,
    pub founded_date_precision: DatePrecision,
    pub dissolved_date: Option<Date>,
    pub dissolved_date_precision: DatePrecision,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::label_founder_history::Entity")]
    LabelFounderHistory,
    #[sea_orm(has_many = "super::label_localized_name_history::Entity")]
    LabelLocalizedNameHistory,
}

impl Related<super::label_founder_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelFounderHistory.def()
    }
}

impl Related<super::label_localized_name_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelLocalizedNameHistory.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::label_founder_history::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::label_founder_history::Relation::LabelHistory
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
