//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod alias_group;
pub mod alias_group_history;
pub mod artist;
pub mod artist_history;
pub mod artist_localized_name;
pub mod credit_role;
pub mod credit_role_history;
pub mod credit_role_inheritance;
pub mod group_member;
pub mod image;
pub mod label;
pub mod label_founder;
pub mod label_history;
pub mod label_localized_name;
pub mod language;
pub mod release;
pub mod release_artist;
pub mod release_credit;
pub mod release_history;
pub mod release_label;
pub mod release_localized_title;
pub mod release_track;
pub mod release_track_artist;
pub mod role;
pub mod sea_orm_active_enums;
pub mod session;
pub mod song;
pub mod song_credit;
pub mod song_history;
pub mod song_localized_title;
pub mod user;
pub mod user_role;
