//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "release_track_artist")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub track_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub artist_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release_track::Entity",
        from = "Column::TrackId",
        to = "super::release_track::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ReleaseTrack,
}

impl Related<super::release_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTrack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
