//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "release_track")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub release_id: i32,
    pub song_id: i32,
    pub track_order: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub track_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release::Entity",
        from = "Column::ReleaseId",
        to = "super::release::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Release,
    #[sea_orm(has_many = "super::release_track_artist::Entity")]
    ReleaseTrackArtist,
}

impl Related<super::release::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Release.def()
    }
}

impl Related<super::release_track_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTrackArtist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
