//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{DatePrecision, ReleaseType};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    juniper :: GraphQLObject,
)]
#[sea_orm(table_name = "release")]
# [graphql (scalar = crate :: extension :: GqlScalarValue)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub release_type: ReleaseType,
    pub release_date: Option<Date>,
    pub release_date_precision: DatePrecision,
    pub recording_date_start: Option<Date>,
    pub recording_date_start_precision: DatePrecision,
    pub recording_date_end: Option<Date>,
    pub recording_date_end_precision: DatePrecision,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::release_artist::Entity")]
    ReleaseArtist,
    #[sea_orm(has_many = "super::release_artist_history::Entity")]
    ReleaseArtistHistory,
    #[sea_orm(has_many = "super::release_credit::Entity")]
    ReleaseCredit,
    #[sea_orm(has_many = "super::release_label::Entity")]
    ReleaseLabel,
    #[sea_orm(has_many = "super::release_label_history::Entity")]
    ReleaseLabelHistory,
    #[sea_orm(has_many = "super::release_localized_title::Entity")]
    ReleaseLocalizedTitle,
    #[sea_orm(has_many = "super::release_localized_title_history::Entity")]
    ReleaseLocalizedTitleHistory,
    #[sea_orm(has_many = "super::release_track::Entity")]
    ReleaseTrack,
    #[sea_orm(has_many = "super::release_track_history::Entity")]
    ReleaseTrackHistory,
}

impl Related<super::release_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseArtist.def()
    }
}

impl Related<super::release_artist_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseArtistHistory.def()
    }
}

impl Related<super::release_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCredit.def()
    }
}

impl Related<super::release_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLabel.def()
    }
}

impl Related<super::release_label_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLabelHistory.def()
    }
}

impl Related<super::release_localized_title::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLocalizedTitle.def()
    }
}

impl Related<super::release_localized_title_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLocalizedTitleHistory.def()
    }
}

impl Related<super::release_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTrack.def()
    }
}

impl Related<super::release_track_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTrackHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
