//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "release_history_track_artist")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub track_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub artist_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artist::Entity",
        from = "Column::ArtistId",
        to = "super::artist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Artist,
    #[sea_orm(
        belongs_to = "super::release_history_track::Entity",
        from = "Column::TrackId",
        to = "super::release_history_track::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReleaseHistoryTrack,
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artist.def()
    }
}

impl Related<super::release_history_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseHistoryTrack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
