//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use juniper::GraphQLObject;
use super::sea_orm_active_enums::DatePrecision;
use super::sea_orm_active_enums::EntityStatus;
use super::sea_orm_active_enums::ReleaseType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, GraphQLObject
)]
#[sea_orm(table_name = "release")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub entity_id: i32,
    pub status: EntityStatus,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub release_type: ReleaseType,
    pub release_date: Option<Date>,
    pub release_date_precision: DatePrecision,
    pub recording_date_start: Option<Date>,
    pub recording_date_precision: DatePrecision,
    pub recording_date_end: Option<Date>,
    pub recording_date_end_precision: DatePrecision,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::release_artist::Entity")]
    ReleaseArtist,
    #[sea_orm(has_many = "super::release_credit::Entity")]
    ReleaseCredit,
    #[sea_orm(has_many = "super::release_label::Entity")]
    ReleaseLabel,
    #[sea_orm(has_many = "super::release_localized_title::Entity")]
    ReleaseLocalizedTitle,
    #[sea_orm(has_many = "super::release_track::Entity")]
    ReleaseTrack,
}

impl Related<super::release_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseArtist.def()
    }
}

impl Related<super::release_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseCredit.def()
    }
}

impl Related<super::release_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLabel.def()
    }
}

impl Related<super::release_localized_title::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseLocalizedTitle.def()
    }
}

impl Related<super::release_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseTrack.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_artist::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_artist::Relation::Release.def().rev())
    }
}

impl Related<super::label::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_label::Relation::Label.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::release_label::Relation::Release.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
