//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ArtistType")]
pub enum ArtistType {
    #[sea_orm(string_value = "Multiple")]
    Multiple,
    #[sea_orm(string_value = "Solo")]
    Solo,
    #[sea_orm(string_value = "Unknown")]
    Unknown,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "CorrectionStatus")]
pub enum CorrectionStatus {
    #[sea_orm(string_value = "Approved")]
    Approved,
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Rejected")]
    Rejected,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "CorrectionType")]
pub enum CorrectionType {
    #[sea_orm(string_value = "Create")]
    Create,
    #[sea_orm(string_value = "Delete")]
    Delete,
    #[sea_orm(string_value = "Update")]
    Update,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "CorrectionUserType"
)]
pub enum CorrectionUserType {
    #[sea_orm(string_value = "Approver")]
    Approver,
    #[sea_orm(string_value = "Author")]
    Author,
    #[sea_orm(string_value = "Co-Author")]
    CoAuthor,
    #[sea_orm(string_value = "Reviewer")]
    Reviewer,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "DatePrecision")]
pub enum DatePrecision {
    #[sea_orm(string_value = "Day")]
    Day,
    #[sea_orm(string_value = "Month")]
    Month,
    #[sea_orm(string_value = "Year")]
    Year,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "EntityType")]
pub enum EntityType {
    #[sea_orm(string_value = "Artist")]
    Artist,
    #[sea_orm(string_value = "Label")]
    Label,
    #[sea_orm(string_value = "Release")]
    Release,
    #[sea_orm(string_value = "Song")]
    Song,
    #[sea_orm(string_value = "Tag")]
    Tag,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ReleaseType")]
pub enum ReleaseType {
    #[sea_orm(string_value = "Album")]
    Album,
    #[sea_orm(string_value = "Compilation")]
    Compilation,
    #[sea_orm(string_value = "Demo")]
    Demo,
    #[sea_orm(string_value = "EP")]
    Ep,
    #[sea_orm(string_value = "Other")]
    Other,
    #[sea_orm(string_value = "Single")]
    Single,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TagKind")]
pub enum TagKind {
    #[sea_orm(string_value = "Descriptor")]
    Descriptor,
    #[sea_orm(string_value = "Form")]
    Form,
    #[sea_orm(string_value = "Genre")]
    Genre,
    #[sea_orm(string_value = "Scene")]
    Scene,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
    Copy,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TagRelationType")]
pub enum TagRelationType {
    #[sea_orm(string_value = "Derive")]
    Derive,
    #[sea_orm(string_value = "Inherit")]
    Inherit,
    #[sea_orm(string_value = "derive")]
    Derive,
    #[sea_orm(string_value = "inherit")]
    Inherit,
}
