ALTER TABLE
  "public"."song_credit"
  DROP CONSTRAINT "song_credit_pkey";

ALTER TABLE
  "public"."song_credit"
ADD
  COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN
  "role_id"
  DROP NOT NULL;

UPDATE
  "public"."song_credit"
SET
  "id" = DEFAULT
WHERE
  "id" IS NULL;

ALTER TABLE
  "public"."song_credit"
ALTER COLUMN
  "id"
SET
  NOT NULL,
ADD
  CONSTRAINT "song_credit_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "uniq_song_credit_credit_role_null" ON "public"."song_credit" ("song_id", "artist_id")
WHERE
  "role_id" IS NULL;

CREATE UNIQUE INDEX "uniq_song_credit_credit_role_not_null" ON "public"."song_credit" ("song_id", "artist_id", "role_id")
WHERE
  "role_id" IS NOT NULL;

ALTER TABLE
  "public"."song_credit_history"
  DROP CONSTRAINT "song_credit_history_pkey";

ALTER TABLE
  "public"."song_credit_history"
ADD
  COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN
  "role_id"
  DROP NOT NULL;

UPDATE
  "public"."song_credit_history"
SET
  "id" = DEFAULT
WHERE
  "id" IS NULL;

ALTER TABLE
  "public"."song_credit_history"
ALTER COLUMN
  "id"
SET
  NOT NULL,
ADD
  CONSTRAINT "song_credit_history_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "uniq_song_credit_history_credit_role_null" ON "public"."song_credit_history" ("history_id", "artist_id")
WHERE
  "role_id" IS NULL;

CREATE UNIQUE INDEX "uniq_song_credit_history_credit_role_not_null" ON "public"."song_credit_history" ("history_id", "artist_id", "role_id")
WHERE
  "role_id" IS NOT NULL;
