[package]
edition = "2024"
name    = "proc_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
darling             = "0.21.0"
itertools.workspace = true
proc-macro2         = "1.0.93"
quote.workspace     = true
syn.workspace       = true
