name: Deploy Dev Server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: nightly

    - name: Build project
      run: cargo build --release

    - name: Set up SCP
      run: |
        mkdir -v -m 700 $HOME/.ssh
        ssh-keyscan -H ${{ secrets.DEV_SSH_HOST }} >> $HOME/.ssh/known_hosts
        echo "${{ secrets.DEV_SSH_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa

    - name: Copy binary to server
      run: |
        scp target/release/thcdb_rs\
        ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }}:~/server/thcdb_rs

    - name: Restart systemd service
      run: |
        ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} \
        "sudo systemctl restart thcdb_rs"
