name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  RUSTFLAGS: "-D warnings"

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mozilla-actions/sccache-action@v0.0.6

    - name: Format
      run: cargo fmt --check --verbose

    - name: Clippy
      run: cargo clippy --verbose

    - name: Test
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose
